sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_df1578915bfc_key -iv $encrypted_df1578915bfc_iv -in gcp-secret.json.enc -out gcp-secret.json -d
- docker build -t tjferrara/docker-react -f Dockerfile.dev .
script:
- docker run tjferrara/docker-react npm run test -- --coverage --watchAll=false
deploy:
  provider: gae
  keyfile: gcp-secret.json
  project: learning-containers-264318
  on:
    branch: master
